//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBestServiceStub.ServiceTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduBestServiceStub.ServiceTests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;![CDATA[&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Melding xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.arkivverket.no/Noark4-1-WS-WD/types&quot;&gt;&lt;journpost xmlns=&quot;&quot;&gt;&lt;jpId&gt;211075&lt;/jpId&gt;&lt;jpJaar&gt;2015&lt;/jpJaar&gt;&lt;jpSeknr&gt;154&lt;/jpSeknr&gt;&lt;jpJpostnr&gt;2&lt;/jpJpostnr&gt;&lt;jpJdato&gt;0001-01-01&lt;/jpJdato&gt;&lt;jpNdoktype&gt;U&lt;/jpNdoktype&gt;&lt;jpDokdato&gt;2015-11-09&lt;/jpDokdato&gt;&lt;jpStatus&gt;R&lt;/jpStatus&gt;&lt;jpInnhold&gt;Dokument 2 test integrasjonspunkt GUR&lt;/jpInnhold&gt;&lt;jpForfdato /&gt;&lt;jpTgkode&gt;U&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EphorteBestEduMessagePayload {
            get {
                return ResourceManager.GetString("EphorteBestEduMessagePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;AppReceipt type=&quot;OK&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.arkivverket.no/Noark/Exchange/types&quot;&amp;gt;&amp;lt;message code=&quot;Recno&quot; xmlns=&quot;&quot;&amp;gt;&amp;lt;text&amp;gt;315635&amp;lt;/text&amp;gt;&amp;lt;/message&amp;gt;&amp;lt;/AppReceipt&amp;gt;.
        /// </summary>
        internal static string P360AppReceiptPayload {
            get {
                return ResourceManager.GetString("P360AppReceiptPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&amp;gt;&amp;lt;Melding xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.arkivverket.no/Noark4-1-WS-WD/types&quot;&amp;gt; &amp;lt;journpost xmlns=&quot;&quot;&amp;gt; &amp;lt;jpId&amp;gt;210707&amp;lt;/jpId&amp;gt; &amp;lt;jpJaar&amp;gt;2015&amp;lt;/jpJaar&amp;gt; &amp;lt;jpSeknr&amp;gt;47&amp;lt;/jpSeknr&amp;gt; &amp;lt;jpJpostnr&amp;gt;7&amp;lt;/jpJpostnr&amp;gt; &amp;lt;jpJdato&amp;gt;0001-01-01&amp;lt;/jpJdato&amp;gt; &amp;lt;jpNdoktype&amp;gt;U&amp;lt;/jpNdoktype&amp;gt; &amp;lt;jpDokdato&amp;gt;2015-09-11&amp;lt;/jpDokdato&amp;gt; &amp;lt;jpS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string P360BestEduMessagePayload {
            get {
                return ResourceManager.GetString("P360BestEduMessagePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&amp;gt;&amp;lt;AppReceipt xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; type=&quot;OK&quot; xmlns=&quot;http://www.arkivverket.no/Noark/Exchange/types&quot;&amp;gt;&amp;lt;message code=&quot;Avsender&quot; xmlns=&quot;&quot;&amp;gt;&amp;lt;text&amp;gt;(810076402)&amp;lt;/text&amp;gt;&amp;lt;/message&amp;gt;&amp;lt;message code=&quot;Mottaker&quot; xmlns=&quot;&quot;&amp;gt;&amp;lt;text&amp;gt;(910077473)&amp;lt;/text&amp;gt;&amp;lt;/message&amp;gt;&amp;lt;message code=&quot;AppKvitteringID&quot; xmlns=&quot;&quot;&amp;gt;&amp;lt;text&amp;gt;bd8e6c5c-05e0-48b4-8a42-2cf71a1742b6&amp;lt;/te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebSakAppReceipt {
            get {
                return ResourceManager.GetString("WebSakAppReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version=&amp;quot;1.0&amp;quot; encoding=&amp;quot;utf-8&amp;quot;?&amp;gt;&amp;lt;Melding xmlns:xsi=&amp;quot;http://www.w3.org/2001/XMLSchema-instance&amp;quot; xmlns:xsd=&amp;quot;http://www.w3.org/2001/XMLSchema&amp;quot; xmlns=&amp;quot;http://www.arkivverket.no/Noark4-1-WS-WD/types&amp;quot;&amp;gt;&amp;lt;journpost xmlns=&amp;quot;&amp;quot;&amp;gt;&amp;lt;jpId&amp;gt;2013002997&amp;lt;/jpId&amp;gt;&amp;lt;jpJaar&amp;gt;2013&amp;lt;/jpJaar&amp;gt;&amp;lt;jpSeknr&amp;gt;2997&amp;lt;/jpSeknr&amp;gt;&amp;lt;jpJdato&amp;gt;2016-04-05&amp;lt;/jpJdato&amp;gt;&amp;lt;jpNdoktype&amp;gt;U&amp;lt;/jpNdoktype&amp;gt;&amp;lt;jpDokdato&amp;gt;2016-04-05&amp;lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebSakBestEduMessagePayload {
            get {
                return ResourceManager.GetString("WebSakBestEduMessagePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version=&amp;quot;1.0&amp;quot; encoding=&amp;quot;utf-8&amp;quot;?&amp;gt;&amp;lt;Melding xmlns:xsi=&amp;quot;http://www.w3.org/2001/XMLSchema-instance&amp;quot; xmlns:xsd=&amp;quot;http://www.w3.org/2001/XMLSchema&amp;quot; xmlns=&amp;quot;http://www.arkivverket.no/Noark4-1-WS-WD/types&amp;quot;&amp;gt;&amp;lt;journpost xmlns=&amp;quot;&amp;quot;&amp;gt;&amp;lt;jpId&amp;gt;2013002997&amp;lt;/jpId&amp;gt;&amp;lt;jpJaar&amp;gt;2013&amp;lt;/jpJaar&amp;gt;&amp;lt;jpSeknr&amp;gt;2997&amp;lt;/jpSeknr&amp;gt;&amp;lt;jpJdato&amp;gt;2016-04-05&amp;lt;/jpJdato&amp;gt;&amp;lt;jpNdoktype&amp;gt;U&amp;lt;/jpNdoktype&amp;gt;&amp;lt;jpDokdato&amp;gt;2016-04-05&amp;lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebSakBestEduMessagePayload2 {
            get {
                return ResourceManager.GetString("WebSakBestEduMessagePayload2", resourceCulture);
            }
        }
    }
}
