//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBestServiceStub.SlackTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduBestServiceStub.SlackTests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Melding xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.arkivverket.no/Noark4-1-WS-WD/types&quot;&gt; &lt;journpost xmlns=&quot;&quot;&gt; &lt;jpId&gt;210707&lt;/jpId&gt; &lt;jpJaar&gt;2015&lt;/jpJaar&gt; &lt;jpSeknr&gt;47&lt;/jpSeknr&gt; &lt;jpJpostnr&gt;7&lt;/jpJpostnr&gt; &lt;jpJdato&gt;0001-01-01&lt;/jpJdato&gt; &lt;jpNdoktype&gt;U&lt;/jpNdoktype&gt; &lt;jpDokdato&gt;2015-09-11&lt;/jpDokdato&gt; &lt;jpStatus&gt;R&lt;/jpStatus&gt; &lt;jpInnhold&gt;Testdokument 7&lt;/jpInnhold&gt; &lt;jpForfdato /&gt; &lt;jpTgkode&gt;U&lt;/jpTgkode&gt; &lt;jpAgdato  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PayloadXml {
            get {
                return ResourceManager.GetString("PayloadXml", resourceCulture);
            }
        }
    }
}
